services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: psw123
      POSTGRES_DB: library
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://user:psw123@db:5432/library
      APP_CONFIG__DB__ECHO: "0"
    ports:
      - "8000:8000"
    command: ["sh", "-c", "alembic upgrade head && uvicorn main:main_app --host 0.0.0.0 --port 8000 --reload"]

volumes:
  db_data:
